var icon = 'icon-value';
var box = 'box';
var ava = 'ava';
var author = 'author';
var added = 'added';
var atext = 'atext';
var source = 'source';
var against = 'against';
var comments = 'comments';
var acontainer = 'acontainer';
export {icon, box, ava, author, added, atext, source, against, comments, acontainer};
